# Generated by Django 2.2.1 on 2019-12-14 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_auto_20191214_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstory',
            name='Published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogstory',
            name='Updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
