# Generated by Django 2.2.1 on 2019-10-23 17:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Introduction', ckeditor.fields.RichTextField()),
                ('Facilities', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=255)),
                ('slug', models.SlugField(help_text='It will auto-complete automically!', max_length=255, unique=True)),
                ('image', models.ImageField(default=None, help_text='enter feature image of post', upload_to='images/blogs')),
                ('content', ckeditor.fields.RichTextField()),
                ('Published_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-Published_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=12)),
                ('Guardain_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='newregisteredimages/')),
                ('DOB', models.DateField()),
                ('College', models.CharField(max_length=255)),
                ('GPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('detail', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default=None, upload_to='images/course')),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.FileField(help_text='upload file', upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of the staff', max_length=255)),
                ('Image', models.ImageField(default=None, help_text='Image of the staff', upload_to='images/faculty_staff')),
                ('Department', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(help_text='Upload file', upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
