# Generated by Django 2.2.1 on 2019-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='', help_text='enter feature image of post', upload_to='images/blogs'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='', upload_to='images/course'),
        ),
        migrations.AlterField(
            model_name='facultystaff',
            name='Image',
            field=models.ImageField(default='', help_text='Image of the staff', upload_to='images/faculty_staff'),
        ),
    ]
