# Generated by Django 2.2.1 on 2019-10-27 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20191023_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', ckeditor.fields.RichTextField()),
                ('career', ckeditor.fields.RichTextField()),
                ('privacy', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
