# Generated by Django 2.2.1 on 2019-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_footer_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
