# Generated by Django 2.2.1 on 2019-12-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_font'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Clientprofile',
        ),
        migrations.DeleteModel(
            name='font',
        ),
    ]
