# Generated by Django 2.2.1 on 2019-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191214_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('Manager', models.CharField(max_length=50)),
                ('image', models.ImageField(height_field=300, upload_to='serviceproviderimages', width_field=600)),
            ],
        ),
    ]
